######################################################################
# Automatically generated by qmake (2.00a) ? 7 6 15:30:22 2006
######################################################################

TEMPLATE = vcapp
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += MainWindow.ui
