#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QDockWidget>
#include <QtGui/QFrame>
#include <QtGui/QGroupBox>
#include <QtGui/QHBoxLayout>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QListWidget>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QRadioButton>
#include <QtGui/QSlider>
#include <QtGui/QStatusBar>
#include <QtGui/QTabWidget>
#include <QtGui/QTextEdit>
#include <QtGui/QVBoxLayout>
#include <QtGui/QWidget>

class Ui_MainWindow : public QMainWindow
{
public:
    QAction *action_New;
    QAction *action_Quit;
    QAction *action_Open;
    QAction *action_About;
    QAction *action_Message;
    QAction *action_Property_Editor;
    QAction *action_Save;
    QAction *action_Save_As;
    QAction *actionRecent;
    QAction *action_Default_Layout;
    QWidget *centralwidget;
    QDockWidget *messageDockWidget;
    QWidget *dockWidgetContents_2;
    QVBoxLayout *vboxLayout;
    QVBoxLayout *vboxLayout1;
    QHBoxLayout *hboxLayout;
    QTextEdit *textEditMessage;
    QDockWidget *propertyDockWidget;
    QWidget *dockWidgetContents;
    QVBoxLayout *vboxLayout2;
    QTabWidget *tabWidget;
    QWidget *tabGeneral;
    QLabel *label_36;
    QGroupBox *groupBox_5;
    QCheckBox *squareCheckBox;
    QCheckBox *bracketCheckBox;
    QCheckBox *sumCheckBox;
    QCheckBox *subtractCheckBox;
    QCheckBox *multiplyCheckBox;
    QCheckBox *modCheckBox;
    QCheckBox *invertCheckBox;
    QCheckBox *factorialCheckBox;
    QGroupBox *groupBox_6;
    QLabel *label_5;
    QLabel *label_29;
    QLabel *label_6;
    QLabel *label_7;
    QSlider *numericRateHorizontalSlider;
    QLabel *numericQtyTextLabel;
    QLabel *operationQtyTextLabel;
    QLabel *label_14;
    QLineEdit *LimitTimeLineEdit;
    QFrame *line;
    QLineEdit *AnswerQuantityLineEdit;
    QPushButton *mixEggPushButton;
    QGroupBox *groupBox_4;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_10;
    QLabel *label_13;
    QLineEdit *numericRangeQuestionToLineEdit;
    QLineEdit *numericRangeAnswerFromLineEdit;
    QLineEdit *numericRangeAnswerToLineEdit;
    QLineEdit *numericRangeQuestionFromLineEdit;
    QWidget *tab_3;
    QGroupBox *groupBox_11;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLineEdit *eggYLineEdit;
    QLineEdit *eggZLineEdit;
    QLineEdit *eggAngleLineEdit;
    QSlider *eggAngleSlider;
    QRadioButton *eggScaleRadioButton;
    QLabel *eggAngleLabel;
    QRadioButton *eggMoveRadioButton;
    QCheckBox *eggConstrainedCheckBox;
    QLineEdit *eggXLineEdit;
    QSlider *eggXSlider;
    QSlider *eggYSlider;
    QSlider *eggZSlider;
    QRadioButton *eggRotateRadioButton;
    QGroupBox *groupBox_7;
    QLabel *label_17;
    QLabel *label_18;
    QLineEdit *containerYLineEdit;
    QLineEdit *containerZLineEdit;
    QLineEdit *containerAngleLineEdit;
    QLabel *containerAngleLabel;
    QRadioButton *containerMoveRadioButton;
    QRadioButton *containerScaleRadioButton;
    QCheckBox *containerConstrainedCheckBox;
    QLabel *label_16;
    QSlider *containerAngleSlider;
    QSlider *containerXSlider;
    QSlider *containerYSlider;
    QSlider *containerZSlider;
    QLineEdit *containerXLineEdit;
    QRadioButton *containerRotateRadioButton;
    QWidget *tab_2;
    QGroupBox *groupBox_3;
    QComboBox *renderTypeComboBox;
    QGroupBox *groupBox_2;
    QComboBox *cameraComboBox;
    QPushButton *setCameraPosPushButton;
    QPushButton *cameraGoStartPosPushButton;
    QLabel *label_35;
    QLabel *label_37;
    QSlider *cameraPosXSlider;
    QLineEdit *cameraPosXLineEdit;
    QSlider *cameraPosYSlider;
    QLabel *label_39;
    QLabel *label_38;
    QSlider *cameraPosZSlider;
    QLineEdit *cameraPosYLineEdit;
    QLineEdit *cameraPosZLineEdit;
    QGroupBox *groupBox;
    QComboBox *skyboxComboBox;
    QPushButton *eggReplacePushButton;
    QLineEdit *eggMeshLineEdit;
    QLabel *label_2;
    QLineEdit *containerMeshLineEdit;
    QPushButton *containerReplacePushButton;
    QLabel *label;
    QLabel *label_3;
    QLabel *label_19;
    QComboBox *containerMaterialComboBox;
    QWidget *tab;
    QGroupBox *groupBox_10;
    QLabel *label_21;
    QLabel *label_25;
    QLineEdit *lightPowerLineEdit;
    QComboBox *lightTypeComboBox;
    QComboBox *lightSelectComboBox;
    QFrame *frame;
    QRadioButton *lightSpecularRadioButton;
    QRadioButton *lightDirectionRadioButton;
    QRadioButton *lightPositionRadioButton;
    QLineEdit *lightZLineEdit;
    QLineEdit *lightYLineEdit;
    QLabel *lightZLabel;
    QLabel *lightYLabel;
    QLabel *lightXLabel;
    QSlider *LightZSlider;
    QSlider *LightYSlider;
    QRadioButton *lightDiffuseRadioButton;
    QSlider *LightXSlider;
    QLineEdit *lightXLineEdit;
    QSlider *lightPowerSlider;
    QPushButton *lightAddPushButton;
    QPushButton *lightDeletePushButton;
    QPushButton *lightRenamePushButton;
    QGroupBox *groupBox_9;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_31;
    QLineEdit *ambientLightBLineEdit;
    QLineEdit *ambientLightGLineEdit;
    QSlider *ambientLightBSlider;
    QSlider *ambientLightGSlider;
    QLineEdit *ambientLightRLineEdit;
    QSlider *ambientLightRSlider;
    QWidget *tab_4;
    QGroupBox *groupBox_8;
    QLabel *label_4;
    QGroupBox *groupBox_13;
    QLabel *label_22;
    QLabel *label_23;
    QLineEdit *fogLinearEndLineEdit;
    QLineEdit *fogLinearStartLineEdit;
    QLabel *label_20;
    QGroupBox *groupBox_12;
    QLabel *label_24;
    QLabel *label_30;
    QLabel *label_40;
    QSlider *fogFadeColorGreenSlider;
    QSlider *fogFadeColorBlueSlider;
    QLabel *fogFadeColorGreenLabel;
    QLabel *fogFadeColorBlueLabel;
    QLabel *fogFadeColorRedLabel;
    QSlider *fogFadeColorRedSlider;
    QComboBox *fogModeComboBox;
    QSlider *fogDensitySlider;
    QGroupBox *groupBox_14;
    QPushButton *materialAddPushButton;
    QPushButton *materialDeletePushButton;
    QLabel *label_34;
    QLabel *label_15;
    QListWidget *materialAllListWidget;
    QListWidget *materialUsingListWidget;
    QLineEdit *fogDensityLineEdit;
    QMenuBar *menubar;
    QMenu *menu_Help;
    QMenu *menuTolls;
    QMenu *menu_File;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
    MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
    MainWindow->resize(QSize(684, 641).expandedTo(MainWindow->minimumSizeHint()));
    QSizePolicy sizePolicy(static_cast<QSizePolicy::Policy>(7), static_cast<QSizePolicy::Policy>(7));
    sizePolicy.setHorizontalStretch(0);
    sizePolicy.setVerticalStretch(0);
    sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
    MainWindow->setSizePolicy(sizePolicy);
    MainWindow->setBaseSize(QSize(0, 0));
    QPalette palette;
    palette.setColor(QPalette::Active, static_cast<QPalette::ColorRole>(0), QColor(0, 0, 0));
    palette.setColor(QPalette::Active, static_cast<QPalette::ColorRole>(1), QColor(255, 255, 255));
    palette.setColor(QPalette::Active, static_cast<QPalette::ColorRole>(2), QColor(255, 255, 255));
    palette.setColor(QPalette::Active, static_cast<QPalette::ColorRole>(3), QColor(255, 255, 255));
    palette.setColor(QPalette::Active, static_cast<QPalette::ColorRole>(4), QColor(127, 127, 127));
    palette.setColor(QPalette::Active, static_cast<QPalette::ColorRole>(5), QColor(170, 170, 170));
    palette.setColor(QPalette::Active, static_cast<QPalette::ColorRole>(6), QColor(0, 0, 0));
    palette.setColor(QPalette::Active, static_cast<QPalette::ColorRole>(7), QColor(255, 255, 255));
    palette.setColor(QPalette::Active, static_cast<QPalette::ColorRole>(8), QColor(0, 0, 0));
    palette.setColor(QPalette::Active, static_cast<QPalette::ColorRole>(9), QColor(255, 255, 255));
    palette.setColor(QPalette::Active, static_cast<QPalette::ColorRole>(10), QColor(255, 255, 255));
    palette.setColor(QPalette::Active, static_cast<QPalette::ColorRole>(11), QColor(0, 0, 0));
    palette.setColor(QPalette::Active, static_cast<QPalette::ColorRole>(12), QColor(49, 106, 197));
    palette.setColor(QPalette::Active, static_cast<QPalette::ColorRole>(13), QColor(255, 255, 255));
    palette.setColor(QPalette::Active, static_cast<QPalette::ColorRole>(14), QColor(0, 0, 255));
    palette.setColor(QPalette::Active, static_cast<QPalette::ColorRole>(15), QColor(255, 0, 255));
    palette.setColor(QPalette::Active, static_cast<QPalette::ColorRole>(16), QColor(255, 255, 255));
    palette.setColor(QPalette::Inactive, static_cast<QPalette::ColorRole>(0), QColor(0, 0, 0));
    palette.setColor(QPalette::Inactive, static_cast<QPalette::ColorRole>(1), QColor(255, 255, 255));
    palette.setColor(QPalette::Inactive, static_cast<QPalette::ColorRole>(2), QColor(255, 255, 255));
    palette.setColor(QPalette::Inactive, static_cast<QPalette::ColorRole>(3), QColor(255, 255, 255));
    palette.setColor(QPalette::Inactive, static_cast<QPalette::ColorRole>(4), QColor(127, 127, 127));
    palette.setColor(QPalette::Inactive, static_cast<QPalette::ColorRole>(5), QColor(170, 170, 170));
    palette.setColor(QPalette::Inactive, static_cast<QPalette::ColorRole>(6), QColor(0, 0, 0));
    palette.setColor(QPalette::Inactive, static_cast<QPalette::ColorRole>(7), QColor(255, 255, 255));
    palette.setColor(QPalette::Inactive, static_cast<QPalette::ColorRole>(8), QColor(0, 0, 0));
    palette.setColor(QPalette::Inactive, static_cast<QPalette::ColorRole>(9), QColor(255, 255, 255));
    palette.setColor(QPalette::Inactive, static_cast<QPalette::ColorRole>(10), QColor(255, 255, 255));
    palette.setColor(QPalette::Inactive, static_cast<QPalette::ColorRole>(11), QColor(0, 0, 0));
    palette.setColor(QPalette::Inactive, static_cast<QPalette::ColorRole>(12), QColor(236, 233, 216));
    palette.setColor(QPalette::Inactive, static_cast<QPalette::ColorRole>(13), QColor(0, 0, 0));
    palette.setColor(QPalette::Inactive, static_cast<QPalette::ColorRole>(14), QColor(0, 0, 255));
    palette.setColor(QPalette::Inactive, static_cast<QPalette::ColorRole>(15), QColor(255, 0, 255));
    palette.setColor(QPalette::Inactive, static_cast<QPalette::ColorRole>(16), QColor(255, 255, 255));
    palette.setColor(QPalette::Disabled, static_cast<QPalette::ColorRole>(0), QColor(127, 127, 127));
    palette.setColor(QPalette::Disabled, static_cast<QPalette::ColorRole>(1), QColor(255, 255, 255));
    palette.setColor(QPalette::Disabled, static_cast<QPalette::ColorRole>(2), QColor(255, 255, 255));
    palette.setColor(QPalette::Disabled, static_cast<QPalette::ColorRole>(3), QColor(255, 255, 255));
    palette.setColor(QPalette::Disabled, static_cast<QPalette::ColorRole>(4), QColor(127, 127, 127));
    palette.setColor(QPalette::Disabled, static_cast<QPalette::ColorRole>(5), QColor(170, 170, 170));
    palette.setColor(QPalette::Disabled, static_cast<QPalette::ColorRole>(6), QColor(127, 127, 127));
    palette.setColor(QPalette::Disabled, static_cast<QPalette::ColorRole>(7), QColor(255, 255, 255));
    palette.setColor(QPalette::Disabled, static_cast<QPalette::ColorRole>(8), QColor(127, 127, 127));
    palette.setColor(QPalette::Disabled, static_cast<QPalette::ColorRole>(9), QColor(255, 255, 255));
    palette.setColor(QPalette::Disabled, static_cast<QPalette::ColorRole>(10), QColor(255, 255, 255));
    palette.setColor(QPalette::Disabled, static_cast<QPalette::ColorRole>(11), QColor(0, 0, 0));
    palette.setColor(QPalette::Disabled, static_cast<QPalette::ColorRole>(12), QColor(49, 106, 197));
    palette.setColor(QPalette::Disabled, static_cast<QPalette::ColorRole>(13), QColor(255, 255, 255));
    palette.setColor(QPalette::Disabled, static_cast<QPalette::ColorRole>(14), QColor(0, 0, 255));
    palette.setColor(QPalette::Disabled, static_cast<QPalette::ColorRole>(15), QColor(255, 0, 255));
    palette.setColor(QPalette::Disabled, static_cast<QPalette::ColorRole>(16), QColor(255, 255, 255));
    MainWindow->setPalette(palette);
    QFont font;
    font.setFamily(QString::fromUtf8("Arial"));
    font.setPointSize(9);
    font.setBold(false);
    font.setItalic(false);
    font.setUnderline(false);
    font.setWeight(50);
    font.setStrikeOut(false);
    MainWindow->setFont(font);
    MainWindow->setFocusPolicy(Qt::NoFocus);
    MainWindow->setAcceptDrops(true);
    MainWindow->setAutoFillBackground(true);
    action_New = new QAction(MainWindow);
    action_New->setObjectName(QString::fromUtf8("action_New"));
    action_Quit = new QAction(MainWindow);
    action_Quit->setObjectName(QString::fromUtf8("action_Quit"));
    action_Open = new QAction(MainWindow);
    action_Open->setObjectName(QString::fromUtf8("action_Open"));
    action_About = new QAction(MainWindow);
    action_About->setObjectName(QString::fromUtf8("action_About"));
    action_Message = new QAction(MainWindow);
    action_Message->setObjectName(QString::fromUtf8("action_Message"));
    action_Message->setCheckable(true);
    action_Message->setChecked(true);
    action_Property_Editor = new QAction(MainWindow);
    action_Property_Editor->setObjectName(QString::fromUtf8("action_Property_Editor"));
    action_Property_Editor->setCheckable(true);
    action_Property_Editor->setChecked(true);
    action_Save = new QAction(MainWindow);
    action_Save->setObjectName(QString::fromUtf8("action_Save"));
    action_Save_As = new QAction(MainWindow);
    action_Save_As->setObjectName(QString::fromUtf8("action_Save_As"));
    actionRecent = new QAction(MainWindow);
    actionRecent->setObjectName(QString::fromUtf8("actionRecent"));
    action_Default_Layout = new QAction(MainWindow);
    action_Default_Layout->setObjectName(QString::fromUtf8("action_Default_Layout"));
    centralwidget = new QWidget(MainWindow);
    centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
    messageDockWidget = new QDockWidget(centralwidget);
    messageDockWidget->setObjectName(QString::fromUtf8("messageDockWidget"));
    messageDockWidget->setGeometry(QRect(20, 100, 201, 121));
    dockWidgetContents_2 = new QWidget(messageDockWidget);
    dockWidgetContents_2->setObjectName(QString::fromUtf8("dockWidgetContents_2"));
    vboxLayout = new QVBoxLayout(dockWidgetContents_2);
    vboxLayout->setSpacing(6);
    vboxLayout->setMargin(9);
    vboxLayout->setObjectName(QString::fromUtf8("vboxLayout"));
    vboxLayout1 = new QVBoxLayout();
    vboxLayout1->setSpacing(6);
    vboxLayout1->setMargin(0);
    vboxLayout1->setObjectName(QString::fromUtf8("vboxLayout1"));
    hboxLayout = new QHBoxLayout();
    hboxLayout->setSpacing(6);
    hboxLayout->setMargin(0);
    hboxLayout->setObjectName(QString::fromUtf8("hboxLayout"));
    textEditMessage = new QTextEdit(dockWidgetContents_2);
    textEditMessage->setObjectName(QString::fromUtf8("textEditMessage"));
    textEditMessage->setFocusPolicy(Qt::StrongFocus);
    textEditMessage->setAutoFormatting(QTextEdit::AutoNone);
    textEditMessage->setTabChangesFocus(true);
    textEditMessage->setUndoRedoEnabled(false);
    textEditMessage->setLineWrapMode(QTextEdit::NoWrap);
    textEditMessage->setReadOnly(true);
    textEditMessage->setAcceptRichText(true);

    hboxLayout->addWidget(textEditMessage);


    vboxLayout1->addLayout(hboxLayout);


    vboxLayout->addLayout(vboxLayout1);

    messageDockWidget->setWidget(dockWidgetContents_2);
    propertyDockWidget = new QDockWidget(centralwidget);
    propertyDockWidget->setObjectName(QString::fromUtf8("propertyDockWidget"));
    propertyDockWidget->setGeometry(QRect(30, 30, 111, 71));
    propertyDockWidget->setMaximumSize(QSize(300, 16777215));
    dockWidgetContents = new QWidget(propertyDockWidget);
    dockWidgetContents->setObjectName(QString::fromUtf8("dockWidgetContents"));
    vboxLayout2 = new QVBoxLayout(dockWidgetContents);
    vboxLayout2->setSpacing(6);
    vboxLayout2->setMargin(9);
    vboxLayout2->setObjectName(QString::fromUtf8("vboxLayout2"));
    propertyDockWidget->setWidget(dockWidgetContents);
    tabWidget = new QTabWidget(centralwidget);
    tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
    tabWidget->setGeometry(QRect(300, 60, 281, 466));
    QSizePolicy sizePolicy1(static_cast<QSizePolicy::Policy>(5), static_cast<QSizePolicy::Policy>(5));
    sizePolicy1.setHorizontalStretch(0);
    sizePolicy1.setVerticalStretch(0);
    sizePolicy1.setHeightForWidth(tabWidget->sizePolicy().hasHeightForWidth());
    tabWidget->setSizePolicy(sizePolicy1);
    tabWidget->setBaseSize(QSize(300, 550));
    tabWidget->setLayoutDirection(Qt::LeftToRight);
    tabWidget->setAutoFillBackground(true);
    tabWidget->setTabPosition(QTabWidget::North);
    tabWidget->setTabShape(QTabWidget::Rounded);
    tabGeneral = new QWidget();
    tabGeneral->setObjectName(QString::fromUtf8("tabGeneral"));
    label_36 = new QLabel(tabGeneral);
    label_36->setObjectName(QString::fromUtf8("label_36"));
    label_36->setGeometry(QRect(20, 370, 56, 13));
    groupBox_5 = new QGroupBox(tabGeneral);
    groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
    groupBox_5->setGeometry(QRect(10, 120, 261, 101));
    squareCheckBox = new QCheckBox(groupBox_5);
    squareCheckBox->setObjectName(QString::fromUtf8("squareCheckBox"));
    squareCheckBox->setGeometry(QRect(10, 60, 82, 17));
    bracketCheckBox = new QCheckBox(groupBox_5);
    bracketCheckBox->setObjectName(QString::fromUtf8("bracketCheckBox"));
    bracketCheckBox->setGeometry(QRect(140, 40, 82, 17));
    sumCheckBox = new QCheckBox(groupBox_5);
    sumCheckBox->setObjectName(QString::fromUtf8("sumCheckBox"));
    sumCheckBox->setGeometry(QRect(10, 20, 82, 17));
    subtractCheckBox = new QCheckBox(groupBox_5);
    subtractCheckBox->setObjectName(QString::fromUtf8("subtractCheckBox"));
    subtractCheckBox->setGeometry(QRect(140, 20, 91, 17));
    subtractCheckBox->setChecked(false);
    multiplyCheckBox = new QCheckBox(groupBox_5);
    multiplyCheckBox->setObjectName(QString::fromUtf8("multiplyCheckBox"));
    multiplyCheckBox->setGeometry(QRect(10, 40, 82, 17));
    modCheckBox = new QCheckBox(groupBox_5);
    modCheckBox->setObjectName(QString::fromUtf8("modCheckBox"));
    modCheckBox->setGeometry(QRect(140, 60, 82, 17));
    invertCheckBox = new QCheckBox(groupBox_5);
    invertCheckBox->setObjectName(QString::fromUtf8("invertCheckBox"));
    invertCheckBox->setGeometry(QRect(140, 80, 82, 17));
    factorialCheckBox = new QCheckBox(groupBox_5);
    factorialCheckBox->setObjectName(QString::fromUtf8("factorialCheckBox"));
    factorialCheckBox->setGeometry(QRect(10, 80, 82, 17));
    groupBox_6 = new QGroupBox(tabGeneral);
    groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
    groupBox_6->setGeometry(QRect(10, 220, 261, 91));
    label_5 = new QLabel(groupBox_6);
    label_5->setObjectName(QString::fromUtf8("label_5"));
    label_5->setGeometry(QRect(10, 20, 81, 16));
    label_29 = new QLabel(groupBox_6);
    label_29->setObjectName(QString::fromUtf8("label_29"));
    label_29->setGeometry(QRect(227, 22, 31, 16));
    label_6 = new QLabel(groupBox_6);
    label_6->setObjectName(QString::fromUtf8("label_6"));
    label_6->setGeometry(QRect(10, 40, 81, 16));
    label_7 = new QLabel(groupBox_6);
    label_7->setObjectName(QString::fromUtf8("label_7"));
    label_7->setGeometry(QRect(10, 60, 81, 16));
    numericRateHorizontalSlider = new QSlider(groupBox_6);
    numericRateHorizontalSlider->setObjectName(QString::fromUtf8("numericRateHorizontalSlider"));
    numericRateHorizontalSlider->setGeometry(QRect(100, 20, 121, 21));
    numericRateHorizontalSlider->setMaximum(100);
    numericRateHorizontalSlider->setPageStep(7);
    numericRateHorizontalSlider->setValue(50);
    numericRateHorizontalSlider->setSliderPosition(50);
    numericRateHorizontalSlider->setOrientation(Qt::Horizontal);
    numericQtyTextLabel = new QLabel(groupBox_6);
    numericQtyTextLabel->setObjectName(QString::fromUtf8("numericQtyTextLabel"));
    numericQtyTextLabel->setGeometry(QRect(100, 40, 71, 20));
    operationQtyTextLabel = new QLabel(groupBox_6);
    operationQtyTextLabel->setObjectName(QString::fromUtf8("operationQtyTextLabel"));
    operationQtyTextLabel->setGeometry(QRect(100, 60, 81, 20));
    label_14 = new QLabel(tabGeneral);
    label_14->setObjectName(QString::fromUtf8("label_14"));
    label_14->setGeometry(QRect(20, 400, 91, 16));
    LimitTimeLineEdit = new QLineEdit(tabGeneral);
    LimitTimeLineEdit->setObjectName(QString::fromUtf8("LimitTimeLineEdit"));
    LimitTimeLineEdit->setGeometry(QRect(120, 370, 141, 22));
    line = new QFrame(tabGeneral);
    line->setObjectName(QString::fromUtf8("line"));
    line->setGeometry(QRect(20, 350, 241, 16));
    line->setFrameShape(QFrame::HLine);
    AnswerQuantityLineEdit = new QLineEdit(tabGeneral);
    AnswerQuantityLineEdit->setObjectName(QString::fromUtf8("AnswerQuantityLineEdit"));
    AnswerQuantityLineEdit->setGeometry(QRect(120, 400, 141, 22));
    mixEggPushButton = new QPushButton(tabGeneral);
    mixEggPushButton->setObjectName(QString::fromUtf8("mixEggPushButton"));
    mixEggPushButton->setGeometry(QRect(10, 320, 261, 23));
    groupBox_4 = new QGroupBox(tabGeneral);
    groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
    groupBox_4->setGeometry(QRect(10, 0, 261, 121));
    label_8 = new QLabel(groupBox_4);
    label_8->setObjectName(QString::fromUtf8("label_8"));
    label_8->setGeometry(QRect(10, 20, 161, 16));
    label_9 = new QLabel(groupBox_4);
    label_9->setObjectName(QString::fromUtf8("label_9"));
    label_9->setGeometry(QRect(30, 40, 31, 16));
    label_11 = new QLabel(groupBox_4);
    label_11->setObjectName(QString::fromUtf8("label_11"));
    label_11->setGeometry(QRect(10, 70, 161, 16));
    label_12 = new QLabel(groupBox_4);
    label_12->setObjectName(QString::fromUtf8("label_12"));
    label_12->setGeometry(QRect(30, 90, 31, 16));
    label_10 = new QLabel(groupBox_4);
    label_10->setObjectName(QString::fromUtf8("label_10"));
    label_10->setGeometry(QRect(140, 40, 16, 16));
    label_13 = new QLabel(groupBox_4);
    label_13->setObjectName(QString::fromUtf8("label_13"));
    label_13->setGeometry(QRect(140, 90, 16, 16));
    numericRangeQuestionToLineEdit = new QLineEdit(groupBox_4);
    numericRangeQuestionToLineEdit->setObjectName(QString::fromUtf8("numericRangeQuestionToLineEdit"));
    numericRangeQuestionToLineEdit->setGeometry(QRect(160, 40, 61, 20));
    numericRangeAnswerFromLineEdit = new QLineEdit(groupBox_4);
    numericRangeAnswerFromLineEdit->setObjectName(QString::fromUtf8("numericRangeAnswerFromLineEdit"));
    numericRangeAnswerFromLineEdit->setGeometry(QRect(60, 90, 61, 20));
    numericRangeAnswerToLineEdit = new QLineEdit(groupBox_4);
    numericRangeAnswerToLineEdit->setObjectName(QString::fromUtf8("numericRangeAnswerToLineEdit"));
    numericRangeAnswerToLineEdit->setGeometry(QRect(160, 90, 61, 20));
    numericRangeQuestionFromLineEdit = new QLineEdit(groupBox_4);
    numericRangeQuestionFromLineEdit->setObjectName(QString::fromUtf8("numericRangeQuestionFromLineEdit"));
    numericRangeQuestionFromLineEdit->setGeometry(QRect(60, 40, 61, 20));
    tabWidget->addTab(tabGeneral, QApplication::translate("MainWindow", "General", 0, QApplication::UnicodeUTF8));
    tab_3 = new QWidget();
    tab_3->setObjectName(QString::fromUtf8("tab_3"));
    groupBox_11 = new QGroupBox(tab_3);
    groupBox_11->setObjectName(QString::fromUtf8("groupBox_11"));
    groupBox_11->setGeometry(QRect(10, 220, 261, 211));
    label_26 = new QLabel(groupBox_11);
    label_26->setObjectName(QString::fromUtf8("label_26"));
    label_26->setGeometry(QRect(10, 20, 16, 16));
    label_27 = new QLabel(groupBox_11);
    label_27->setObjectName(QString::fromUtf8("label_27"));
    label_27->setGeometry(QRect(10, 50, 16, 16));
    label_28 = new QLabel(groupBox_11);
    label_28->setObjectName(QString::fromUtf8("label_28"));
    label_28->setGeometry(QRect(10, 80, 16, 16));
    eggYLineEdit = new QLineEdit(groupBox_11);
    eggYLineEdit->setObjectName(QString::fromUtf8("eggYLineEdit"));
    eggYLineEdit->setGeometry(QRect(214, 47, 41, 22));
    eggZLineEdit = new QLineEdit(groupBox_11);
    eggZLineEdit->setObjectName(QString::fromUtf8("eggZLineEdit"));
    eggZLineEdit->setGeometry(QRect(214, 76, 41, 22));
    eggAngleLineEdit = new QLineEdit(groupBox_11);
    eggAngleLineEdit->setObjectName(QString::fromUtf8("eggAngleLineEdit"));
    eggAngleLineEdit->setEnabled(false);
    eggAngleLineEdit->setGeometry(QRect(214, 106, 41, 22));
    eggAngleSlider = new QSlider(groupBox_11);
    eggAngleSlider->setObjectName(QString::fromUtf8("eggAngleSlider"));
    eggAngleSlider->setEnabled(false);
    eggAngleSlider->setGeometry(QRect(50, 110, 161, 21));
    eggAngleSlider->setMinimum(-180);
    eggAngleSlider->setMaximum(180);
    eggAngleSlider->setOrientation(Qt::Horizontal);
    eggAngleSlider->setInvertedAppearance(false);
    eggScaleRadioButton = new QRadioButton(groupBox_11);
    eggScaleRadioButton->setObjectName(QString::fromUtf8("eggScaleRadioButton"));
    eggScaleRadioButton->setGeometry(QRect(190, 170, 61, 17));
    eggAngleLabel = new QLabel(groupBox_11);
    eggAngleLabel->setObjectName(QString::fromUtf8("eggAngleLabel"));
    eggAngleLabel->setEnabled(false);
    eggAngleLabel->setGeometry(QRect(10, 110, 31, 16));
    eggMoveRadioButton = new QRadioButton(groupBox_11);
    eggMoveRadioButton->setObjectName(QString::fromUtf8("eggMoveRadioButton"));
    eggMoveRadioButton->setGeometry(QRect(20, 170, 71, 17));
    eggMoveRadioButton->setChecked(true);
    eggConstrainedCheckBox = new QCheckBox(groupBox_11);
    eggConstrainedCheckBox->setObjectName(QString::fromUtf8("eggConstrainedCheckBox"));
    eggConstrainedCheckBox->setEnabled(false);
    eggConstrainedCheckBox->setGeometry(QRect(20, 140, 171, 17));
    eggConstrainedCheckBox->setChecked(true);
    eggXLineEdit = new QLineEdit(groupBox_11);
    eggXLineEdit->setObjectName(QString::fromUtf8("eggXLineEdit"));
    eggXLineEdit->setGeometry(QRect(213, 18, 41, 22));
    eggXSlider = new QSlider(groupBox_11);
    eggXSlider->setObjectName(QString::fromUtf8("eggXSlider"));
    eggXSlider->setGeometry(QRect(50, 20, 161, 21));
    eggXSlider->setMinimum(-300);
    eggXSlider->setMaximum(300);
    eggXSlider->setOrientation(Qt::Horizontal);
    eggYSlider = new QSlider(groupBox_11);
    eggYSlider->setObjectName(QString::fromUtf8("eggYSlider"));
    eggYSlider->setGeometry(QRect(50, 50, 161, 21));
    eggYSlider->setMinimum(-300);
    eggYSlider->setMaximum(300);
    eggYSlider->setOrientation(Qt::Horizontal);
    eggZSlider = new QSlider(groupBox_11);
    eggZSlider->setObjectName(QString::fromUtf8("eggZSlider"));
    eggZSlider->setGeometry(QRect(50, 80, 161, 21));
    eggZSlider->setMinimum(-300);
    eggZSlider->setMaximum(300);
    eggZSlider->setOrientation(Qt::Horizontal);
    eggRotateRadioButton = new QRadioButton(groupBox_11);
    eggRotateRadioButton->setObjectName(QString::fromUtf8("eggRotateRadioButton"));
    eggRotateRadioButton->setEnabled(false);
    eggRotateRadioButton->setGeometry(QRect(110, 170, 71, 17));
    groupBox_7 = new QGroupBox(tab_3);
    groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
    groupBox_7->setGeometry(QRect(10, 10, 261, 201));
    label_17 = new QLabel(groupBox_7);
    label_17->setObjectName(QString::fromUtf8("label_17"));
    label_17->setGeometry(QRect(10, 50, 16, 16));
    label_18 = new QLabel(groupBox_7);
    label_18->setObjectName(QString::fromUtf8("label_18"));
    label_18->setGeometry(QRect(10, 80, 16, 16));
    containerYLineEdit = new QLineEdit(groupBox_7);
    containerYLineEdit->setObjectName(QString::fromUtf8("containerYLineEdit"));
    containerYLineEdit->setGeometry(QRect(213, 49, 41, 22));
    containerZLineEdit = new QLineEdit(groupBox_7);
    containerZLineEdit->setObjectName(QString::fromUtf8("containerZLineEdit"));
    containerZLineEdit->setGeometry(QRect(213, 78, 41, 22));
    containerAngleLineEdit = new QLineEdit(groupBox_7);
    containerAngleLineEdit->setObjectName(QString::fromUtf8("containerAngleLineEdit"));
    containerAngleLineEdit->setEnabled(false);
    containerAngleLineEdit->setGeometry(QRect(213, 107, 41, 22));
    containerAngleLabel = new QLabel(groupBox_7);
    containerAngleLabel->setObjectName(QString::fromUtf8("containerAngleLabel"));
    containerAngleLabel->setEnabled(false);
    containerAngleLabel->setGeometry(QRect(10, 110, 31, 16));
    containerMoveRadioButton = new QRadioButton(groupBox_7);
    containerMoveRadioButton->setObjectName(QString::fromUtf8("containerMoveRadioButton"));
    containerMoveRadioButton->setGeometry(QRect(20, 170, 71, 17));
    containerMoveRadioButton->setChecked(true);
    containerScaleRadioButton = new QRadioButton(groupBox_7);
    containerScaleRadioButton->setObjectName(QString::fromUtf8("containerScaleRadioButton"));
    containerScaleRadioButton->setGeometry(QRect(180, 170, 61, 17));
    containerConstrainedCheckBox = new QCheckBox(groupBox_7);
    containerConstrainedCheckBox->setObjectName(QString::fromUtf8("containerConstrainedCheckBox"));
    containerConstrainedCheckBox->setEnabled(false);
    containerConstrainedCheckBox->setGeometry(QRect(20, 140, 171, 17));
    containerConstrainedCheckBox->setChecked(true);
    label_16 = new QLabel(groupBox_7);
    label_16->setObjectName(QString::fromUtf8("label_16"));
    label_16->setGeometry(QRect(10, 20, 31, 16));
    containerAngleSlider = new QSlider(groupBox_7);
    containerAngleSlider->setObjectName(QString::fromUtf8("containerAngleSlider"));
    containerAngleSlider->setEnabled(false);
    containerAngleSlider->setGeometry(QRect(50, 110, 161, 21));
    containerAngleSlider->setMinimum(-180);
    containerAngleSlider->setMaximum(180);
    containerAngleSlider->setOrientation(Qt::Horizontal);
    containerAngleSlider->setInvertedAppearance(false);
    containerXSlider = new QSlider(groupBox_7);
    containerXSlider->setObjectName(QString::fromUtf8("containerXSlider"));
    containerXSlider->setGeometry(QRect(50, 20, 161, 21));
    containerXSlider->setMinimum(-300);
    containerXSlider->setMaximum(300);
    containerXSlider->setOrientation(Qt::Horizontal);
    containerYSlider = new QSlider(groupBox_7);
    containerYSlider->setObjectName(QString::fromUtf8("containerYSlider"));
    containerYSlider->setGeometry(QRect(50, 50, 161, 21));
    containerYSlider->setMinimum(-300);
    containerYSlider->setMaximum(300);
    containerYSlider->setOrientation(Qt::Horizontal);
    containerZSlider = new QSlider(groupBox_7);
    containerZSlider->setObjectName(QString::fromUtf8("containerZSlider"));
    containerZSlider->setGeometry(QRect(50, 80, 161, 21));
    containerZSlider->setMinimum(-300);
    containerZSlider->setMaximum(300);
    containerZSlider->setOrientation(Qt::Horizontal);
    containerXLineEdit = new QLineEdit(groupBox_7);
    containerXLineEdit->setObjectName(QString::fromUtf8("containerXLineEdit"));
    containerXLineEdit->setGeometry(QRect(213, 20, 41, 22));
    containerRotateRadioButton = new QRadioButton(groupBox_7);
    containerRotateRadioButton->setObjectName(QString::fromUtf8("containerRotateRadioButton"));
    containerRotateRadioButton->setEnabled(false);
    containerRotateRadioButton->setGeometry(QRect(100, 170, 71, 17));
    tabWidget->addTab(tab_3, QApplication::translate("MainWindow", "Object", 0, QApplication::UnicodeUTF8));
    tab_2 = new QWidget();
    tab_2->setObjectName(QString::fromUtf8("tab_2"));
    groupBox_3 = new QGroupBox(tab_2);
    groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
    groupBox_3->setGeometry(QRect(10, 380, 261, 51));
    renderTypeComboBox = new QComboBox(groupBox_3);
    renderTypeComboBox->setObjectName(QString::fromUtf8("renderTypeComboBox"));
    renderTypeComboBox->setGeometry(QRect(10, 20, 241, 22));
    groupBox_2 = new QGroupBox(tab_2);
    groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
    groupBox_2->setGeometry(QRect(10, 150, 261, 221));
    cameraComboBox = new QComboBox(groupBox_2);
    cameraComboBox->setObjectName(QString::fromUtf8("cameraComboBox"));
    cameraComboBox->setGeometry(QRect(10, 20, 241, 22));
    setCameraPosPushButton = new QPushButton(groupBox_2);
    setCameraPosPushButton->setObjectName(QString::fromUtf8("setCameraPosPushButton"));
    setCameraPosPushButton->setGeometry(QRect(10, 50, 241, 23));
    cameraGoStartPosPushButton = new QPushButton(groupBox_2);
    cameraGoStartPosPushButton->setObjectName(QString::fromUtf8("cameraGoStartPosPushButton"));
    cameraGoStartPosPushButton->setGeometry(QRect(10, 80, 241, 23));
    label_35 = new QLabel(groupBox_2);
    label_35->setObjectName(QString::fromUtf8("label_35"));
    label_35->setGeometry(QRect(10, 110, 91, 16));
    label_37 = new QLabel(groupBox_2);
    label_37->setObjectName(QString::fromUtf8("label_37"));
    label_37->setGeometry(QRect(20, 130, 16, 16));
    cameraPosXSlider = new QSlider(groupBox_2);
    cameraPosXSlider->setObjectName(QString::fromUtf8("cameraPosXSlider"));
    cameraPosXSlider->setGeometry(QRect(40, 130, 161, 21));
    cameraPosXSlider->setMinimum(-1000);
    cameraPosXSlider->setMaximum(1000);
    cameraPosXSlider->setOrientation(Qt::Horizontal);
    cameraPosXLineEdit = new QLineEdit(groupBox_2);
    cameraPosXLineEdit->setObjectName(QString::fromUtf8("cameraPosXLineEdit"));
    cameraPosXLineEdit->setGeometry(QRect(210, 130, 41, 22));
    cameraPosYSlider = new QSlider(groupBox_2);
    cameraPosYSlider->setObjectName(QString::fromUtf8("cameraPosYSlider"));
    cameraPosYSlider->setGeometry(QRect(40, 160, 161, 21));
    cameraPosYSlider->setMinimum(-1000);
    cameraPosYSlider->setMaximum(1000);
    cameraPosYSlider->setOrientation(Qt::Horizontal);
    label_39 = new QLabel(groupBox_2);
    label_39->setObjectName(QString::fromUtf8("label_39"));
    label_39->setGeometry(QRect(20, 160, 16, 16));
    label_38 = new QLabel(groupBox_2);
    label_38->setObjectName(QString::fromUtf8("label_38"));
    label_38->setGeometry(QRect(20, 190, 16, 16));
    cameraPosZSlider = new QSlider(groupBox_2);
    cameraPosZSlider->setObjectName(QString::fromUtf8("cameraPosZSlider"));
    cameraPosZSlider->setGeometry(QRect(40, 190, 161, 21));
    cameraPosZSlider->setMinimum(-1000);
    cameraPosZSlider->setMaximum(1000);
    cameraPosZSlider->setOrientation(Qt::Horizontal);
    cameraPosYLineEdit = new QLineEdit(groupBox_2);
    cameraPosYLineEdit->setObjectName(QString::fromUtf8("cameraPosYLineEdit"));
    cameraPosYLineEdit->setGeometry(QRect(210, 160, 41, 22));
    cameraPosZLineEdit = new QLineEdit(groupBox_2);
    cameraPosZLineEdit->setObjectName(QString::fromUtf8("cameraPosZLineEdit"));
    cameraPosZLineEdit->setGeometry(QRect(210, 190, 41, 22));
    groupBox = new QGroupBox(tab_2);
    groupBox->setObjectName(QString::fromUtf8("groupBox"));
    groupBox->setGeometry(QRect(10, 10, 261, 141));
    skyboxComboBox = new QComboBox(groupBox);
    skyboxComboBox->setObjectName(QString::fromUtf8("skyboxComboBox"));
    skyboxComboBox->setGeometry(QRect(70, 110, 181, 22));
    eggReplacePushButton = new QPushButton(groupBox);
    eggReplacePushButton->setObjectName(QString::fromUtf8("eggReplacePushButton"));
    eggReplacePushButton->setGeometry(QRect(220, 80, 31, 23));
    eggMeshLineEdit = new QLineEdit(groupBox);
    eggMeshLineEdit->setObjectName(QString::fromUtf8("eggMeshLineEdit"));
    eggMeshLineEdit->setGeometry(QRect(70, 80, 151, 22));
    label_2 = new QLabel(groupBox);
    label_2->setObjectName(QString::fromUtf8("label_2"));
    label_2->setGeometry(QRect(10, 80, 56, 13));
    containerMeshLineEdit = new QLineEdit(groupBox);
    containerMeshLineEdit->setObjectName(QString::fromUtf8("containerMeshLineEdit"));
    containerMeshLineEdit->setGeometry(QRect(70, 20, 151, 22));
    containerReplacePushButton = new QPushButton(groupBox);
    containerReplacePushButton->setObjectName(QString::fromUtf8("containerReplacePushButton"));
    containerReplacePushButton->setGeometry(QRect(220, 20, 31, 23));
    label = new QLabel(groupBox);
    label->setObjectName(QString::fromUtf8("label"));
    label->setGeometry(QRect(10, 20, 56, 13));
    label_3 = new QLabel(groupBox);
    label_3->setObjectName(QString::fromUtf8("label_3"));
    label_3->setGeometry(QRect(10, 110, 56, 13));
    label_19 = new QLabel(groupBox);
    label_19->setObjectName(QString::fromUtf8("label_19"));
    label_19->setGeometry(QRect(6, 40, 59, 40));
    containerMaterialComboBox = new QComboBox(groupBox);
    containerMaterialComboBox->setObjectName(QString::fromUtf8("containerMaterialComboBox"));
    containerMaterialComboBox->setGeometry(QRect(70, 50, 181, 22));
    tabWidget->addTab(tab_2, QApplication::translate("MainWindow", "World", 0, QApplication::UnicodeUTF8));
    tab = new QWidget();
    tab->setObjectName(QString::fromUtf8("tab"));
    groupBox_10 = new QGroupBox(tab);
    groupBox_10->setObjectName(QString::fromUtf8("groupBox_10"));
    groupBox_10->setGeometry(QRect(10, 130, 261, 301));
    label_21 = new QLabel(groupBox_10);
    label_21->setObjectName(QString::fromUtf8("label_21"));
    label_21->setGeometry(QRect(10, 270, 41, 16));
    label_25 = new QLabel(groupBox_10);
    label_25->setObjectName(QString::fromUtf8("label_25"));
    label_25->setGeometry(QRect(10, 240, 56, 13));
    lightPowerLineEdit = new QLineEdit(groupBox_10);
    lightPowerLineEdit->setObjectName(QString::fromUtf8("lightPowerLineEdit"));
    lightPowerLineEdit->setGeometry(QRect(200, 240, 51, 22));
    lightTypeComboBox = new QComboBox(groupBox_10);
    lightTypeComboBox->setObjectName(QString::fromUtf8("lightTypeComboBox"));
    lightTypeComboBox->setGeometry(QRect(60, 270, 191, 22));
    lightSelectComboBox = new QComboBox(groupBox_10);
    lightSelectComboBox->setObjectName(QString::fromUtf8("lightSelectComboBox"));
    lightSelectComboBox->setGeometry(QRect(10, 20, 241, 22));
    frame = new QFrame(groupBox_10);
    frame->setObjectName(QString::fromUtf8("frame"));
    frame->setGeometry(QRect(10, 80, 241, 151));
    frame->setFrameShape(QFrame::Box);
    frame->setFrameShadow(QFrame::Raised);
    lightSpecularRadioButton = new QRadioButton(frame);
    lightSpecularRadioButton->setObjectName(QString::fromUtf8("lightSpecularRadioButton"));
    lightSpecularRadioButton->setGeometry(QRect(140, 100, 91, 17));
    lightDirectionRadioButton = new QRadioButton(frame);
    lightDirectionRadioButton->setObjectName(QString::fromUtf8("lightDirectionRadioButton"));
    lightDirectionRadioButton->setGeometry(QRect(30, 120, 91, 17));
    lightPositionRadioButton = new QRadioButton(frame);
    lightPositionRadioButton->setObjectName(QString::fromUtf8("lightPositionRadioButton"));
    lightPositionRadioButton->setGeometry(QRect(140, 120, 91, 17));
    lightZLineEdit = new QLineEdit(frame);
    lightZLineEdit->setObjectName(QString::fromUtf8("lightZLineEdit"));
    lightZLineEdit->setGeometry(QRect(186, 68, 51, 22));
    lightYLineEdit = new QLineEdit(frame);
    lightYLineEdit->setObjectName(QString::fromUtf8("lightYLineEdit"));
    lightYLineEdit->setGeometry(QRect(186, 39, 51, 22));
    lightZLabel = new QLabel(frame);
    lightZLabel->setObjectName(QString::fromUtf8("lightZLabel"));
    lightZLabel->setGeometry(QRect(10, 70, 16, 16));
    lightYLabel = new QLabel(frame);
    lightYLabel->setObjectName(QString::fromUtf8("lightYLabel"));
    lightYLabel->setGeometry(QRect(10, 40, 16, 16));
    lightXLabel = new QLabel(frame);
    lightXLabel->setObjectName(QString::fromUtf8("lightXLabel"));
    lightXLabel->setGeometry(QRect(10, 10, 16, 16));
    LightZSlider = new QSlider(frame);
    LightZSlider->setObjectName(QString::fromUtf8("LightZSlider"));
    LightZSlider->setGeometry(QRect(30, 70, 151, 21));
    LightZSlider->setMaximum(100);
    LightZSlider->setPageStep(10);
    LightZSlider->setValue(100);
    LightZSlider->setSliderPosition(100);
    LightZSlider->setOrientation(Qt::Horizontal);
    LightYSlider = new QSlider(frame);
    LightYSlider->setObjectName(QString::fromUtf8("LightYSlider"));
    LightYSlider->setGeometry(QRect(30, 40, 151, 21));
    LightYSlider->setMinimum(0);
    LightYSlider->setMaximum(100);
    LightYSlider->setPageStep(10);
    LightYSlider->setValue(100);
    LightYSlider->setSliderPosition(100);
    LightYSlider->setOrientation(Qt::Horizontal);
    lightDiffuseRadioButton = new QRadioButton(frame);
    lightDiffuseRadioButton->setObjectName(QString::fromUtf8("lightDiffuseRadioButton"));
    lightDiffuseRadioButton->setGeometry(QRect(30, 100, 91, 17));
    lightDiffuseRadioButton->setChecked(true);
    LightXSlider = new QSlider(frame);
    LightXSlider->setObjectName(QString::fromUtf8("LightXSlider"));
    LightXSlider->setGeometry(QRect(30, 10, 151, 21));
    LightXSlider->setMaximum(100);
    LightXSlider->setPageStep(10);
    LightXSlider->setValue(100);
    LightXSlider->setSliderPosition(100);
    LightXSlider->setOrientation(Qt::Horizontal);
    lightXLineEdit = new QLineEdit(frame);
    lightXLineEdit->setObjectName(QString::fromUtf8("lightXLineEdit"));
    lightXLineEdit->setGeometry(QRect(186, 10, 51, 22));
    lightPowerSlider = new QSlider(groupBox_10);
    lightPowerSlider->setObjectName(QString::fromUtf8("lightPowerSlider"));
    lightPowerSlider->setGeometry(QRect(60, 240, 131, 21));
    lightPowerSlider->setMaximum(100);
    lightPowerSlider->setPageStep(10);
    lightPowerSlider->setOrientation(Qt::Horizontal);
    lightAddPushButton = new QPushButton(groupBox_10);
    lightAddPushButton->setObjectName(QString::fromUtf8("lightAddPushButton"));
    lightAddPushButton->setEnabled(false);
    lightAddPushButton->setGeometry(QRect(10, 50, 75, 23));
    lightDeletePushButton = new QPushButton(groupBox_10);
    lightDeletePushButton->setObjectName(QString::fromUtf8("lightDeletePushButton"));
    lightDeletePushButton->setEnabled(false);
    lightDeletePushButton->setGeometry(QRect(90, 50, 75, 23));
    lightRenamePushButton = new QPushButton(groupBox_10);
    lightRenamePushButton->setObjectName(QString::fromUtf8("lightRenamePushButton"));
    lightRenamePushButton->setEnabled(false);
    lightRenamePushButton->setGeometry(QRect(170, 50, 75, 23));
    groupBox_9 = new QGroupBox(tab);
    groupBox_9->setObjectName(QString::fromUtf8("groupBox_9"));
    groupBox_9->setGeometry(QRect(10, 10, 261, 111));
    label_32 = new QLabel(groupBox_9);
    label_32->setObjectName(QString::fromUtf8("label_32"));
    label_32->setGeometry(QRect(20, 20, 16, 16));
    label_33 = new QLabel(groupBox_9);
    label_33->setObjectName(QString::fromUtf8("label_33"));
    label_33->setGeometry(QRect(20, 50, 16, 16));
    label_31 = new QLabel(groupBox_9);
    label_31->setObjectName(QString::fromUtf8("label_31"));
    label_31->setGeometry(QRect(20, 80, 16, 16));
    ambientLightBLineEdit = new QLineEdit(groupBox_9);
    ambientLightBLineEdit->setObjectName(QString::fromUtf8("ambientLightBLineEdit"));
    ambientLightBLineEdit->setGeometry(QRect(207, 77, 51, 22));
    ambientLightGLineEdit = new QLineEdit(groupBox_9);
    ambientLightGLineEdit->setObjectName(QString::fromUtf8("ambientLightGLineEdit"));
    ambientLightGLineEdit->setGeometry(QRect(207, 48, 51, 22));
    ambientLightBSlider = new QSlider(groupBox_9);
    ambientLightBSlider->setObjectName(QString::fromUtf8("ambientLightBSlider"));
    ambientLightBSlider->setGeometry(QRect(40, 80, 161, 21));
    ambientLightBSlider->setMaximum(100);
    ambientLightBSlider->setPageStep(10);
    ambientLightBSlider->setValue(100);
    ambientLightBSlider->setSliderPosition(100);
    ambientLightBSlider->setOrientation(Qt::Horizontal);
    ambientLightGSlider = new QSlider(groupBox_9);
    ambientLightGSlider->setObjectName(QString::fromUtf8("ambientLightGSlider"));
    ambientLightGSlider->setGeometry(QRect(40, 50, 161, 21));
    ambientLightGSlider->setMinimum(0);
    ambientLightGSlider->setMaximum(100);
    ambientLightGSlider->setPageStep(10);
    ambientLightGSlider->setValue(100);
    ambientLightGSlider->setSliderPosition(100);
    ambientLightGSlider->setOrientation(Qt::Horizontal);
    ambientLightRLineEdit = new QLineEdit(groupBox_9);
    ambientLightRLineEdit->setObjectName(QString::fromUtf8("ambientLightRLineEdit"));
    ambientLightRLineEdit->setGeometry(QRect(207, 20, 51, 22));
    ambientLightRSlider = new QSlider(groupBox_9);
    ambientLightRSlider->setObjectName(QString::fromUtf8("ambientLightRSlider"));
    ambientLightRSlider->setGeometry(QRect(40, 20, 161, 21));
    ambientLightRSlider->setMaximum(100);
    ambientLightRSlider->setPageStep(12);
    ambientLightRSlider->setValue(100);
    ambientLightRSlider->setSliderPosition(100);
    ambientLightRSlider->setOrientation(Qt::Horizontal);
    tabWidget->addTab(tab, QApplication::translate("MainWindow", "Light", 0, QApplication::UnicodeUTF8));
    tab_4 = new QWidget();
    tab_4->setObjectName(QString::fromUtf8("tab_4"));
    groupBox_8 = new QGroupBox(tab_4);
    groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
    groupBox_8->setGeometry(QRect(10, 0, 261, 241));
    label_4 = new QLabel(groupBox_8);
    label_4->setObjectName(QString::fromUtf8("label_4"));
    label_4->setGeometry(QRect(10, 50, 56, 13));
    groupBox_13 = new QGroupBox(groupBox_8);
    groupBox_13->setObjectName(QString::fromUtf8("groupBox_13"));
    groupBox_13->setGeometry(QRect(10, 70, 241, 51));
    label_22 = new QLabel(groupBox_13);
    label_22->setObjectName(QString::fromUtf8("label_22"));
    label_22->setGeometry(QRect(10, 20, 31, 16));
    label_23 = new QLabel(groupBox_13);
    label_23->setObjectName(QString::fromUtf8("label_23"));
    label_23->setGeometry(QRect(130, 20, 31, 16));
    fogLinearEndLineEdit = new QLineEdit(groupBox_13);
    fogLinearEndLineEdit->setObjectName(QString::fromUtf8("fogLinearEndLineEdit"));
    fogLinearEndLineEdit->setGeometry(QRect(160, 20, 71, 22));
    fogLinearStartLineEdit = new QLineEdit(groupBox_13);
    fogLinearStartLineEdit->setObjectName(QString::fromUtf8("fogLinearStartLineEdit"));
    fogLinearStartLineEdit->setGeometry(QRect(40, 20, 71, 22));
    label_20 = new QLabel(groupBox_8);
    label_20->setObjectName(QString::fromUtf8("label_20"));
    label_20->setGeometry(QRect(10, 20, 31, 16));
    groupBox_12 = new QGroupBox(groupBox_8);
    groupBox_12->setObjectName(QString::fromUtf8("groupBox_12"));
    groupBox_12->setGeometry(QRect(10, 120, 241, 111));
    label_24 = new QLabel(groupBox_12);
    label_24->setObjectName(QString::fromUtf8("label_24"));
    label_24->setGeometry(QRect(10, 20, 16, 16));
    label_30 = new QLabel(groupBox_12);
    label_30->setObjectName(QString::fromUtf8("label_30"));
    label_30->setGeometry(QRect(10, 50, 16, 16));
    label_40 = new QLabel(groupBox_12);
    label_40->setObjectName(QString::fromUtf8("label_40"));
    label_40->setGeometry(QRect(10, 80, 16, 16));
    fogFadeColorGreenSlider = new QSlider(groupBox_12);
    fogFadeColorGreenSlider->setObjectName(QString::fromUtf8("fogFadeColorGreenSlider"));
    fogFadeColorGreenSlider->setGeometry(QRect(30, 50, 161, 21));
    fogFadeColorGreenSlider->setMaximum(100);
    fogFadeColorGreenSlider->setOrientation(Qt::Horizontal);
    fogFadeColorBlueSlider = new QSlider(groupBox_12);
    fogFadeColorBlueSlider->setObjectName(QString::fromUtf8("fogFadeColorBlueSlider"));
    fogFadeColorBlueSlider->setGeometry(QRect(30, 80, 161, 21));
    fogFadeColorBlueSlider->setMaximum(101);
    fogFadeColorBlueSlider->setOrientation(Qt::Horizontal);
    fogFadeColorGreenLabel = new QLabel(groupBox_12);
    fogFadeColorGreenLabel->setObjectName(QString::fromUtf8("fogFadeColorGreenLabel"));
    fogFadeColorGreenLabel->setGeometry(QRect(190, 50, 41, 20));
    fogFadeColorGreenLabel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    fogFadeColorBlueLabel = new QLabel(groupBox_12);
    fogFadeColorBlueLabel->setObjectName(QString::fromUtf8("fogFadeColorBlueLabel"));
    fogFadeColorBlueLabel->setGeometry(QRect(190, 80, 41, 20));
    fogFadeColorBlueLabel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    fogFadeColorRedLabel = new QLabel(groupBox_12);
    fogFadeColorRedLabel->setObjectName(QString::fromUtf8("fogFadeColorRedLabel"));
    fogFadeColorRedLabel->setGeometry(QRect(190, 20, 41, 20));
    fogFadeColorRedLabel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    fogFadeColorRedSlider = new QSlider(groupBox_12);
    fogFadeColorRedSlider->setObjectName(QString::fromUtf8("fogFadeColorRedSlider"));
    fogFadeColorRedSlider->setGeometry(QRect(30, 20, 161, 21));
    fogFadeColorRedSlider->setMaximum(100);
    fogFadeColorRedSlider->setOrientation(Qt::Horizontal);
    fogModeComboBox = new QComboBox(groupBox_8);
    fogModeComboBox->setObjectName(QString::fromUtf8("fogModeComboBox"));
    fogModeComboBox->setGeometry(QRect(60, 20, 191, 22));
    fogDensitySlider = new QSlider(groupBox_8);
    fogDensitySlider->setObjectName(QString::fromUtf8("fogDensitySlider"));
    fogDensitySlider->setGeometry(QRect(60, 50, 121, 21));
    fogDensitySlider->setMaximum(1000000);
    fogDensitySlider->setOrientation(Qt::Horizontal);
    groupBox_14 = new QGroupBox(tab_4);
    groupBox_14->setObjectName(QString::fromUtf8("groupBox_14"));
    groupBox_14->setGeometry(QRect(10, 240, 261, 191));
    materialAddPushButton = new QPushButton(groupBox_14);
    materialAddPushButton->setObjectName(QString::fromUtf8("materialAddPushButton"));
    materialAddPushButton->setGeometry(QRect(10, 90, 121, 21));
    materialDeletePushButton = new QPushButton(groupBox_14);
    materialDeletePushButton->setObjectName(QString::fromUtf8("materialDeletePushButton"));
    materialDeletePushButton->setGeometry(QRect(130, 90, 121, 21));
    label_34 = new QLabel(groupBox_14);
    label_34->setObjectName(QString::fromUtf8("label_34"));
    label_34->setGeometry(QRect(10, 113, 101, 16));
    label_15 = new QLabel(groupBox_14);
    label_15->setObjectName(QString::fromUtf8("label_15"));
    label_15->setGeometry(QRect(10, 17, 111, 16));
    materialAllListWidget = new QListWidget(groupBox_14);
    materialAllListWidget->setObjectName(QString::fromUtf8("materialAllListWidget"));
    materialAllListWidget->setGeometry(QRect(10, 34, 241, 53));
    materialUsingListWidget = new QListWidget(groupBox_14);
    materialUsingListWidget->setObjectName(QString::fromUtf8("materialUsingListWidget"));
    materialUsingListWidget->setGeometry(QRect(10, 130, 241, 53));
    fogDensityLineEdit = new QLineEdit(tab_4);
    fogDensityLineEdit->setObjectName(QString::fromUtf8("fogDensityLineEdit"));
    fogDensityLineEdit->setGeometry(QRect(200, 50, 61, 22));
    tabWidget->addTab(tab_4, QApplication::translate("MainWindow", "Material", 0, QApplication::UnicodeUTF8));
    MainWindow->setCentralWidget(centralwidget);
    menubar = new QMenuBar(MainWindow);
    menubar->setObjectName(QString::fromUtf8("menubar"));
    menubar->setGeometry(QRect(0, 0, 684, 20));
    menu_Help = new QMenu(menubar);
    menu_Help->setObjectName(QString::fromUtf8("menu_Help"));
    menuTolls = new QMenu(menubar);
    menuTolls->setObjectName(QString::fromUtf8("menuTolls"));
    menu_File = new QMenu(menubar);
    menu_File->setObjectName(QString::fromUtf8("menu_File"));
    MainWindow->setMenuBar(menubar);
    statusbar = new QStatusBar(MainWindow);
    statusbar->setObjectName(QString::fromUtf8("statusbar"));
    MainWindow->setStatusBar(statusbar);
    QWidget::setTabOrder(ambientLightRLineEdit, squareCheckBox);
    QWidget::setTabOrder(squareCheckBox, bracketCheckBox);
    QWidget::setTabOrder(bracketCheckBox, sumCheckBox);
    QWidget::setTabOrder(sumCheckBox, subtractCheckBox);
    QWidget::setTabOrder(subtractCheckBox, multiplyCheckBox);
    QWidget::setTabOrder(multiplyCheckBox, modCheckBox);
    QWidget::setTabOrder(modCheckBox, invertCheckBox);
    QWidget::setTabOrder(invertCheckBox, factorialCheckBox);
    QWidget::setTabOrder(factorialCheckBox, numericRateHorizontalSlider);
    QWidget::setTabOrder(numericRateHorizontalSlider, mixEggPushButton);
    QWidget::setTabOrder(mixEggPushButton, LimitTimeLineEdit);
    QWidget::setTabOrder(LimitTimeLineEdit, numericRangeQuestionFromLineEdit);
    QWidget::setTabOrder(numericRangeQuestionFromLineEdit, numericRangeQuestionToLineEdit);
    QWidget::setTabOrder(numericRangeQuestionToLineEdit, numericRangeAnswerFromLineEdit);
    QWidget::setTabOrder(numericRangeAnswerFromLineEdit, numericRangeAnswerToLineEdit);
    QWidget::setTabOrder(numericRangeAnswerToLineEdit, AnswerQuantityLineEdit);
    QWidget::setTabOrder(AnswerQuantityLineEdit, eggYLineEdit);
    QWidget::setTabOrder(eggYLineEdit, eggZLineEdit);
    QWidget::setTabOrder(eggZLineEdit, eggAngleLineEdit);
    QWidget::setTabOrder(eggAngleLineEdit, eggAngleSlider);
    QWidget::setTabOrder(eggAngleSlider, eggRotateRadioButton);
    QWidget::setTabOrder(eggRotateRadioButton, eggScaleRadioButton);
    QWidget::setTabOrder(eggScaleRadioButton, eggMoveRadioButton);
    QWidget::setTabOrder(eggMoveRadioButton, eggConstrainedCheckBox);
    QWidget::setTabOrder(eggConstrainedCheckBox, eggXLineEdit);
    QWidget::setTabOrder(eggXLineEdit, eggXSlider);
    QWidget::setTabOrder(eggXSlider, eggYSlider);
    QWidget::setTabOrder(eggYSlider, eggZSlider);
    QWidget::setTabOrder(eggZSlider, containerYLineEdit);
    QWidget::setTabOrder(containerYLineEdit, containerZLineEdit);
    QWidget::setTabOrder(containerZLineEdit, containerAngleLineEdit);
    QWidget::setTabOrder(containerAngleLineEdit, containerMoveRadioButton);
    QWidget::setTabOrder(containerMoveRadioButton, containerRotateRadioButton);
    QWidget::setTabOrder(containerRotateRadioButton, containerScaleRadioButton);
    QWidget::setTabOrder(containerScaleRadioButton, containerConstrainedCheckBox);
    QWidget::setTabOrder(containerConstrainedCheckBox, containerAngleSlider);
    QWidget::setTabOrder(containerAngleSlider, containerXSlider);
    QWidget::setTabOrder(containerXSlider, containerYSlider);
    QWidget::setTabOrder(containerYSlider, containerZSlider);
    QWidget::setTabOrder(containerZSlider, containerXLineEdit);
    QWidget::setTabOrder(containerXLineEdit, eggMeshLineEdit);
    QWidget::setTabOrder(eggMeshLineEdit, containerReplacePushButton);
    QWidget::setTabOrder(containerReplacePushButton, eggReplacePushButton);
    QWidget::setTabOrder(eggReplacePushButton, skyboxComboBox);
    QWidget::setTabOrder(skyboxComboBox, containerMeshLineEdit);
    QWidget::setTabOrder(containerMeshLineEdit, renderTypeComboBox);
    QWidget::setTabOrder(renderTypeComboBox, cameraPosYLineEdit);
    QWidget::setTabOrder(cameraPosYLineEdit, cameraPosZLineEdit);
    QWidget::setTabOrder(cameraPosZLineEdit, cameraPosYSlider);
    QWidget::setTabOrder(cameraPosYSlider, cameraPosZSlider);
    QWidget::setTabOrder(cameraPosZSlider, cameraComboBox);
    QWidget::setTabOrder(cameraComboBox, cameraGoStartPosPushButton);
    QWidget::setTabOrder(cameraGoStartPosPushButton, cameraPosXLineEdit);
    QWidget::setTabOrder(cameraPosXLineEdit, cameraPosXSlider);
    QWidget::setTabOrder(cameraPosXSlider, setCameraPosPushButton);
    QWidget::setTabOrder(setCameraPosPushButton, lightAddPushButton);
    QWidget::setTabOrder(lightAddPushButton, lightDeletePushButton);
    QWidget::setTabOrder(lightDeletePushButton, lightRenamePushButton);
    QWidget::setTabOrder(lightRenamePushButton, lightPowerLineEdit);
    QWidget::setTabOrder(lightPowerLineEdit, lightTypeComboBox);
    QWidget::setTabOrder(lightTypeComboBox, lightSelectComboBox);
    QWidget::setTabOrder(lightSelectComboBox, lightSpecularRadioButton);
    QWidget::setTabOrder(lightSpecularRadioButton, lightDirectionRadioButton);
    QWidget::setTabOrder(lightDirectionRadioButton, lightPositionRadioButton);
    QWidget::setTabOrder(lightPositionRadioButton, lightZLineEdit);
    QWidget::setTabOrder(lightZLineEdit, lightYLineEdit);
    QWidget::setTabOrder(lightYLineEdit, LightZSlider);
    QWidget::setTabOrder(LightZSlider, LightYSlider);
    QWidget::setTabOrder(LightYSlider, lightDiffuseRadioButton);
    QWidget::setTabOrder(lightDiffuseRadioButton, LightXSlider);
    QWidget::setTabOrder(LightXSlider, lightXLineEdit);
    QWidget::setTabOrder(lightXLineEdit, lightPowerSlider);
    QWidget::setTabOrder(lightPowerSlider, ambientLightBLineEdit);
    QWidget::setTabOrder(ambientLightBLineEdit, ambientLightGLineEdit);
    QWidget::setTabOrder(ambientLightGLineEdit, ambientLightBSlider);
    QWidget::setTabOrder(ambientLightBSlider, ambientLightGSlider);
    QWidget::setTabOrder(ambientLightGSlider, ambientLightRSlider);
    QWidget::setTabOrder(ambientLightRSlider, tabWidget);
    QWidget::setTabOrder(tabWidget, materialUsingListWidget);
    QWidget::setTabOrder(materialUsingListWidget, materialAddPushButton);
    QWidget::setTabOrder(materialAddPushButton, materialDeletePushButton);
    QWidget::setTabOrder(materialDeletePushButton, materialAllListWidget);
    QWidget::setTabOrder(materialAllListWidget, textEditMessage);

    menubar->addAction(menu_File->menuAction());
    menubar->addAction(menuTolls->menuAction());
    menubar->addAction(menu_Help->menuAction());
    menu_Help->addAction(action_About);
    menuTolls->addAction(action_Property_Editor);
    menuTolls->addAction(action_Message);
    menuTolls->addSeparator();
    menuTolls->addAction(action_Default_Layout);
    menu_File->addAction(action_New);
    menu_File->addAction(action_Open);
    menu_File->addAction(actionRecent);
    menu_File->addSeparator();
    menu_File->addAction(action_Save);
    menu_File->addAction(action_Save_As);
    menu_File->addSeparator();
    menu_File->addAction(action_Quit);
    retranslateUi(MainWindow);
    QObject::connect(action_Quit, SIGNAL(triggered()), MainWindow, SLOT(close()));

    tabWidget->setCurrentIndex(0);


    QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
    MainWindow->setWindowTitle(QApplication::translate("MainWindow", "Builder", 0, QApplication::UnicodeUTF8));
    action_New->setText(QApplication::translate("MainWindow", "&New", 0, QApplication::UnicodeUTF8));
    action_New->setShortcut(QApplication::translate("MainWindow", "Ctrl+N", 0, QApplication::UnicodeUTF8));
    action_Quit->setText(QApplication::translate("MainWindow", "&Quit", 0, QApplication::UnicodeUTF8));
    action_Quit->setShortcut(QApplication::translate("MainWindow", "Ctrl+Q", 0, QApplication::UnicodeUTF8));
    action_Open->setText(QApplication::translate("MainWindow", "&Open", 0, QApplication::UnicodeUTF8));
    action_Open->setShortcut(QApplication::translate("MainWindow", "Ctrl+O", 0, QApplication::UnicodeUTF8));
    action_About->setText(QApplication::translate("MainWindow", "&About", 0, QApplication::UnicodeUTF8));
    action_Message->setText(QApplication::translate("MainWindow", "&Message", 0, QApplication::UnicodeUTF8));
    action_Message->setShortcut(QApplication::translate("MainWindow", "Ctrl+M", 0, QApplication::UnicodeUTF8));
    action_Property_Editor->setText(QApplication::translate("MainWindow", "&Property Editor", 0, QApplication::UnicodeUTF8));
    action_Property_Editor->setShortcut(QApplication::translate("MainWindow", "Ctrl+P", 0, QApplication::UnicodeUTF8));
    action_Save->setText(QApplication::translate("MainWindow", "&Save", 0, QApplication::UnicodeUTF8));
    action_Save->setShortcut(QApplication::translate("MainWindow", "Ctrl+S", 0, QApplication::UnicodeUTF8));
    action_Save_As->setText(QApplication::translate("MainWindow", "Save &As ...", 0, QApplication::UnicodeUTF8));
    actionRecent->setText(QApplication::translate("MainWindow", "Recent", 0, QApplication::UnicodeUTF8));
    action_Default_Layout->setText(QApplication::translate("MainWindow", "&Default Layout", 0, QApplication::UnicodeUTF8));
    messageDockWidget->setWindowTitle(QApplication::translate("MainWindow", "Message", 0, QApplication::UnicodeUTF8));
    propertyDockWidget->setWindowTitle(QApplication::translate("MainWindow", "Property", 0, QApplication::UnicodeUTF8));
    label_36->setText(QApplication::translate("MainWindow", "Limit time", 0, QApplication::UnicodeUTF8));
    groupBox_5->setTitle(QApplication::translate("MainWindow", "Operator", 0, QApplication::UnicodeUTF8));
    squareCheckBox->setText(QApplication::translate("MainWindow", "^ square", 0, QApplication::UnicodeUTF8));
    bracketCheckBox->setText(QApplication::translate("MainWindow", "() bracket", 0, QApplication::UnicodeUTF8));
    sumCheckBox->setText(QApplication::translate("MainWindow", "+ sum", 0, QApplication::UnicodeUTF8));
    subtractCheckBox->setText(QApplication::translate("MainWindow", "- subtract", 0, QApplication::UnicodeUTF8));
    multiplyCheckBox->setText(QApplication::translate("MainWindow", "* multiply", 0, QApplication::UnicodeUTF8));
    modCheckBox->setText(QApplication::translate("MainWindow", "% mod", 0, QApplication::UnicodeUTF8));
    invertCheckBox->setText(QApplication::translate("MainWindow", "~ invert", 0, QApplication::UnicodeUTF8));
    factorialCheckBox->setText(QApplication::translate("MainWindow", "! factorial", 0, QApplication::UnicodeUTF8));
    groupBox_6->setTitle(QApplication::translate("MainWindow", "Display rate numeric && operation", 0, QApplication::UnicodeUTF8));
    label_5->setText(QApplication::translate("MainWindow", "Numeric Rate", 0, QApplication::UnicodeUTF8));
    label_29->setText(QApplication::translate("MainWindow", "100%", 0, QApplication::UnicodeUTF8));
    label_6->setText(QApplication::translate("MainWindow", "Numeric Qty.", 0, QApplication::UnicodeUTF8));
    label_7->setText(QApplication::translate("MainWindow", "Operator Qty.", 0, QApplication::UnicodeUTF8));
    numericQtyTextLabel->setText(QApplication::translate("MainWindow", "TextLabel", 0, QApplication::UnicodeUTF8));
    operationQtyTextLabel->setText(QApplication::translate("MainWindow", "TextLabel", 0, QApplication::UnicodeUTF8));
    label_14->setText(QApplication::translate("MainWindow", "Answer Quantity", 0, QApplication::UnicodeUTF8));
    mixEggPushButton->setText(QApplication::translate("MainWindow", "&Mix Egg", 0, QApplication::UnicodeUTF8));
    groupBox_4->setTitle(QApplication::translate("MainWindow", "Value", 0, QApplication::UnicodeUTF8));
    label_8->setText(QApplication::translate("MainWindow", "Numeric range for question", 0, QApplication::UnicodeUTF8));
    label_9->setText(QApplication::translate("MainWindow", "from", 0, QApplication::UnicodeUTF8));
    label_11->setText(QApplication::translate("MainWindow", "Numeric range for answer", 0, QApplication::UnicodeUTF8));
    label_12->setText(QApplication::translate("MainWindow", "from", 0, QApplication::UnicodeUTF8));
    label_10->setText(QApplication::translate("MainWindow", "to", 0, QApplication::UnicodeUTF8));
    label_13->setText(QApplication::translate("MainWindow", "to", 0, QApplication::UnicodeUTF8));
    numericRangeQuestionFromLineEdit->setToolTip(QApplication::translate("MainWindow", "\354\240\200\354\236\245\355\225\230\354\204\270\354\232\224 ^^", 0, QApplication::UnicodeUTF8));
    tabWidget->setTabText(tabWidget->indexOf(tabGeneral), QApplication::translate("MainWindow", "General", 0, QApplication::UnicodeUTF8));
    groupBox_11->setTitle(QApplication::translate("MainWindow", "Egg", 0, QApplication::UnicodeUTF8));
    label_26->setText(QApplication::translate("MainWindow", "x", 0, QApplication::UnicodeUTF8));
    label_27->setText(QApplication::translate("MainWindow", "y", 0, QApplication::UnicodeUTF8));
    label_28->setText(QApplication::translate("MainWindow", "z", 0, QApplication::UnicodeUTF8));
    eggYLineEdit->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
    eggZLineEdit->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
    eggAngleLineEdit->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
    eggScaleRadioButton->setText(QApplication::translate("MainWindow", "scale", 0, QApplication::UnicodeUTF8));
    eggAngleLabel->setText(QApplication::translate("MainWindow", "angle", 0, QApplication::UnicodeUTF8));
    eggMoveRadioButton->setText(QApplication::translate("MainWindow", "position", 0, QApplication::UnicodeUTF8));
    eggConstrainedCheckBox->setText(QApplication::translate("MainWindow", "constrained aspect ratio", 0, QApplication::UnicodeUTF8));
    eggXLineEdit->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
    eggRotateRadioButton->setToolTip(QApplication::translate("MainWindow", "under construcion...", 0, QApplication::UnicodeUTF8));
    eggRotateRadioButton->setText(QApplication::translate("MainWindow", "rotate", 0, QApplication::UnicodeUTF8));
    groupBox_7->setTitle(QApplication::translate("MainWindow", "Container", 0, QApplication::UnicodeUTF8));
    label_17->setText(QApplication::translate("MainWindow", "y", 0, QApplication::UnicodeUTF8));
    label_18->setText(QApplication::translate("MainWindow", "z", 0, QApplication::UnicodeUTF8));
    containerYLineEdit->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
    containerZLineEdit->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
    containerAngleLineEdit->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
    containerAngleLabel->setText(QApplication::translate("MainWindow", "angle", 0, QApplication::UnicodeUTF8));
    containerMoveRadioButton->setText(QApplication::translate("MainWindow", "position", 0, QApplication::UnicodeUTF8));
    containerScaleRadioButton->setText(QApplication::translate("MainWindow", "scale", 0, QApplication::UnicodeUTF8));
    containerConstrainedCheckBox->setText(QApplication::translate("MainWindow", "constrained aspect ratio", 0, QApplication::UnicodeUTF8));
    label_16->setText(QApplication::translate("MainWindow", "x", 0, QApplication::UnicodeUTF8));
    containerXLineEdit->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
    containerRotateRadioButton->setToolTip(QApplication::translate("MainWindow", "under construcion...", 0, QApplication::UnicodeUTF8));
    containerRotateRadioButton->setText(QApplication::translate("MainWindow", "rotate", 0, QApplication::UnicodeUTF8));
    tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("MainWindow", "Object", 0, QApplication::UnicodeUTF8));
    groupBox_3->setTitle(QApplication::translate("MainWindow", "Render", 0, QApplication::UnicodeUTF8));
    renderTypeComboBox->clear();
    renderTypeComboBox->addItem(QApplication::translate("MainWindow", "Solid", 0, QApplication::UnicodeUTF8));
    renderTypeComboBox->addItem(QApplication::translate("MainWindow", "Wireframe", 0, QApplication::UnicodeUTF8));
    renderTypeComboBox->addItem(QApplication::translate("MainWindow", "Point", 0, QApplication::UnicodeUTF8));
    groupBox_2->setTitle(QApplication::translate("MainWindow", "Camera", 0, QApplication::UnicodeUTF8));
    cameraComboBox->clear();
    cameraComboBox->addItem(QApplication::translate("MainWindow", "Left", 0, QApplication::UnicodeUTF8));
    cameraComboBox->addItem(QApplication::translate("MainWindow", "Right", 0, QApplication::UnicodeUTF8));
    cameraComboBox->addItem(QApplication::translate("MainWindow", "Front", 0, QApplication::UnicodeUTF8));
    cameraComboBox->addItem(QApplication::translate("MainWindow", "Back", 0, QApplication::UnicodeUTF8));
    cameraComboBox->addItem(QApplication::translate("MainWindow", "Upon", 0, QApplication::UnicodeUTF8));
    cameraComboBox->addItem(QApplication::translate("MainWindow", "Below", 0, QApplication::UnicodeUTF8));
    setCameraPosPushButton->setText(QApplication::translate("MainWindow", "&Set start position", 0, QApplication::UnicodeUTF8));
    cameraGoStartPosPushButton->setText(QApplication::translate("MainWindow", "&Go start position", 0, QApplication::UnicodeUTF8));
    label_35->setText(QApplication::translate("MainWindow", "position adjust", 0, QApplication::UnicodeUTF8));
    label_37->setText(QApplication::translate("MainWindow", "x", 0, QApplication::UnicodeUTF8));
    cameraPosXLineEdit->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
    label_39->setText(QApplication::translate("MainWindow", "y", 0, QApplication::UnicodeUTF8));
    label_38->setText(QApplication::translate("MainWindow", "z", 0, QApplication::UnicodeUTF8));
    cameraPosYLineEdit->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
    cameraPosZLineEdit->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
    groupBox->setTitle(QApplication::translate("MainWindow", "Object", 0, QApplication::UnicodeUTF8));
    eggReplacePushButton->setText(QApplication::translate("MainWindow", "...", 0, QApplication::UnicodeUTF8));
    eggMeshLineEdit->setText(QApplication::translate("MainWindow", "mesh file", 0, QApplication::UnicodeUTF8));
    label_2->setText(QApplication::translate("MainWindow", "egg", 0, QApplication::UnicodeUTF8));
    containerMeshLineEdit->setText(QApplication::translate("MainWindow", "mesh file", 0, QApplication::UnicodeUTF8));
    containerReplacePushButton->setText(QApplication::translate("MainWindow", "...", 0, QApplication::UnicodeUTF8));
    label->setText(QApplication::translate("MainWindow", "container", 0, QApplication::UnicodeUTF8));
    label_3->setText(QApplication::translate("MainWindow", "sky box", 0, QApplication::UnicodeUTF8));
    label_19->setText(QApplication::translate("MainWindow", "container<br>material", 0, QApplication::UnicodeUTF8));
    tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "World", 0, QApplication::UnicodeUTF8));
    groupBox_10->setTitle(QApplication::translate("MainWindow", "Light", 0, QApplication::UnicodeUTF8));
    label_21->setText(QApplication::translate("MainWindow", "Type", 0, QApplication::UnicodeUTF8));
    label_25->setText(QApplication::translate("MainWindow", "Power", 0, QApplication::UnicodeUTF8));
    lightTypeComboBox->clear();
    lightTypeComboBox->addItem(QApplication::translate("MainWindow", "Point", 0, QApplication::UnicodeUTF8));
    lightTypeComboBox->addItem(QApplication::translate("MainWindow", "Directional", 0, QApplication::UnicodeUTF8));
    lightTypeComboBox->addItem(QApplication::translate("MainWindow", "Spotlight", 0, QApplication::UnicodeUTF8));
    lightSpecularRadioButton->setText(QApplication::translate("MainWindow", "Specular", 0, QApplication::UnicodeUTF8));
    lightDirectionRadioButton->setText(QApplication::translate("MainWindow", "Direction", 0, QApplication::UnicodeUTF8));
    lightPositionRadioButton->setText(QApplication::translate("MainWindow", "Position", 0, QApplication::UnicodeUTF8));
    lightZLabel->setText(QApplication::translate("MainWindow", "b", 0, QApplication::UnicodeUTF8));
    lightYLabel->setText(QApplication::translate("MainWindow", "g", 0, QApplication::UnicodeUTF8));
    lightXLabel->setText(QApplication::translate("MainWindow", "r", 0, QApplication::UnicodeUTF8));
    lightDiffuseRadioButton->setText(QApplication::translate("MainWindow", "Diffuse", 0, QApplication::UnicodeUTF8));
    lightAddPushButton->setToolTip(QApplication::translate("MainWindow", "under construcion...", 0, QApplication::UnicodeUTF8));
    lightAddPushButton->setText(QApplication::translate("MainWindow", "&Add", 0, QApplication::UnicodeUTF8));
    lightDeletePushButton->setToolTip(QApplication::translate("MainWindow", "under construcion...", 0, QApplication::UnicodeUTF8));
    lightDeletePushButton->setText(QApplication::translate("MainWindow", "&Delete", 0, QApplication::UnicodeUTF8));
    lightRenamePushButton->setToolTip(QApplication::translate("MainWindow", "under construcion...", 0, QApplication::UnicodeUTF8));
    lightRenamePushButton->setText(QApplication::translate("MainWindow", "&Rename", 0, QApplication::UnicodeUTF8));
    groupBox_9->setTitle(QApplication::translate("MainWindow", "Ambient Light", 0, QApplication::UnicodeUTF8));
    label_32->setText(QApplication::translate("MainWindow", "r", 0, QApplication::UnicodeUTF8));
    label_33->setText(QApplication::translate("MainWindow", "g", 0, QApplication::UnicodeUTF8));
    label_31->setText(QApplication::translate("MainWindow", "b", 0, QApplication::UnicodeUTF8));
    tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "Light", 0, QApplication::UnicodeUTF8));
    groupBox_8->setTitle(QApplication::translate("MainWindow", "Fog", 0, QApplication::UnicodeUTF8));
    label_4->setText(QApplication::translate("MainWindow", "Density", 0, QApplication::UnicodeUTF8));
    groupBox_13->setTitle(QApplication::translate("MainWindow", "Linear", 0, QApplication::UnicodeUTF8));
    label_22->setText(QApplication::translate("MainWindow", "Start", 0, QApplication::UnicodeUTF8));
    label_23->setText(QApplication::translate("MainWindow", "End", 0, QApplication::UnicodeUTF8));
    label_20->setText(QApplication::translate("MainWindow", "Mode", 0, QApplication::UnicodeUTF8));
    groupBox_12->setTitle(QApplication::translate("MainWindow", "Fade Color", 0, QApplication::UnicodeUTF8));
    label_24->setText(QApplication::translate("MainWindow", "r", 0, QApplication::UnicodeUTF8));
    label_30->setText(QApplication::translate("MainWindow", "g", 0, QApplication::UnicodeUTF8));
    label_40->setText(QApplication::translate("MainWindow", "b", 0, QApplication::UnicodeUTF8));
    fogFadeColorGreenLabel->setText(QApplication::translate("MainWindow", "0.001", 0, QApplication::UnicodeUTF8));
    fogFadeColorBlueLabel->setText(QApplication::translate("MainWindow", "0.001", 0, QApplication::UnicodeUTF8));
    fogFadeColorRedLabel->setText(QApplication::translate("MainWindow", "0.001", 0, QApplication::UnicodeUTF8));
    groupBox_14->setTitle(QApplication::translate("MainWindow", "Material", 0, QApplication::UnicodeUTF8));
    materialAddPushButton->setText(QApplication::translate("MainWindow", "\342\210\250", 0, QApplication::UnicodeUTF8));
    materialDeletePushButton->setText(QApplication::translate("MainWindow", "\342\210\247", 0, QApplication::UnicodeUTF8));
    label_34->setText(QApplication::translate("MainWindow", "Using Material", 0, QApplication::UnicodeUTF8));
    label_15->setText(QApplication::translate("MainWindow", "Unusing Material", 0, QApplication::UnicodeUTF8));
    tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("MainWindow", "Material", 0, QApplication::UnicodeUTF8));
    menu_Help->setTitle(QApplication::translate("MainWindow", "&Help", 0, QApplication::UnicodeUTF8));
    menuTolls->setTitle(QApplication::translate("MainWindow", "&Tools", 0, QApplication::UnicodeUTF8));
    menu_File->setTitle(QApplication::translate("MainWindow", "&File", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

#endif // UI_MAINWINDOW_H
